# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Shared VLM processing helpers for Energon and HF dataset paths."""

from __future__ import annotations

import copy
import re
import warnings
from collections.abc import Mapping, MutableMapping, Sequence
from dataclasses import dataclass
from typing import Any

import torch

from megatron.bridge.data.datasets.utils import GENERATION_REGEX, IGNORE_INDEX
from megatron.bridge.training.utils.visual_inputs import GenericVisualInputs


CHATML_ASSISTANT_ROLE = "assistant"


@dataclass(frozen=True)
class AssistantMaskBoundaryConfig:
    """Token boundary fallback configuration for assistant loss masks.

    Expected input format:
        ``role_start_tokens`` maps each chat role to the token-id sequence that
        immediately precedes that role's content in already-rendered
        ``input_ids``. ``role_end_tokens`` maps each chat role to the token-id
        sequence that terminates that role's turn. ``loss_roles`` names
        top-level chat roles that should contribute to loss. This follows the
        common SFT convention used by chat-template based pipelines: once a role
        contributes to loss, the role's full rendered content contributes,
        including formatted tool-call or reasoning spans inside that role.
        ``include_*_tokens_for_roles`` optionally include boundary tokens in the
        loss. By default, assistant turn end tokens are included because they
        are generated by the assistant and teach the model when to stop.

        Example::

            AssistantMaskBoundaryConfig(
                role_start_tokens={"user": [10], "assistant": [11]},
                role_end_tokens={"user": [12], "assistant": [12]},
                loss_roles=("assistant",),
                include_end_tokens_for_roles=("assistant",),
                trim_leading_token_ids=(198,),
            )

    Output format:
        When passed to :func:`build_assistant_loss_mask`, the fallback scans
        rendered ``input_ids`` for role boundaries and returns an
        unshifted float mask with ``1.0`` only on role spans whose role appears
        in ``loss_roles``. Boundary marker tokens are included only when
        requested by the corresponding ``include_*`` fields.
    """

    role_start_tokens: Mapping[str, Sequence[int]]
    role_end_tokens: Mapping[str, Sequence[int]]
    loss_roles: Sequence[str] = (CHATML_ASSISTANT_ROLE,)
    include_start_tokens_for_roles: Sequence[str] = ()
    include_end_tokens_for_roles: Sequence[str] = (CHATML_ASSISTANT_ROLE,)
    trim_leading_token_ids: Sequence[int] = ()


@dataclass(frozen=True)
class NormalizedVLMSample:
    """Source-normalized VLM sample consumed by shared processing.

    Expected input format:
        Instances are produced by source adapters such as
        :func:`normalize_energon_vlm_sample` and
        :func:`normalize_hf_vlm_example`.  ``conversation`` must be a structured
        list of chat turns in HF processor format, for example::

            [
                {"role": "user", "content": "describe <image>"},
                {"role": "assistant", "content": "a red car"},
            ]

        ``content`` may also be a multimodal content list accepted by
        ``processor.apply_chat_template``, for example::

            [{"type": "image", "image": image_obj}, {"type": "text", "text": "describe"}]

        ``images`` and ``videos`` are optional processor-ready modality payloads.
        Energon adapters convert WDS tensors to PIL objects before populating
        these fields; HF adapters may leave them ``None`` when media already lives
        inline in ``conversation`` content.

    Output format:
        Shared processing treats this as the single boundary contract before
        model-specific tokenization and vision preprocessing.  It does not
        contain batched tensors; model-specific collators convert it into model
        input tensors.
    """

    conversation: list[dict[str, Any]]
    images: list[Any] | None = None
    videos: list[Any] | None = None
    audio: Any | None = None


def normalize_energon_vlm_sample(sample: Any) -> NormalizedVLMSample:
    """Normalize an Energon ``ChatMLSample`` into the shared VLM sample contract.

    Expected input format:
        ``sample`` is expected to expose the Energon ``ChatMLSample`` fields:

        - ``conversation``: JSON string accepted by ``cook_chatml_sample``.  The
          JSON may use either ``{"role": ..., "content": ...}`` turns or
          ``{"from": ..., "value": ...}`` turns.
        - ``imgs``: optional WDS decoded image tensor/list payload.
        - ``videos``: optional WDS decoded video tensor/list payload.
        - ``audio``: optional audio payload, passed through unchanged.

    Output format:
        Returns ``NormalizedVLMSample`` where ``conversation`` is a list of
        ``{"role": str, "content": str | list[dict]}`` turns, ``images`` are
        PIL/list processor inputs or ``None``, ``videos`` are nested PIL/list
        processor inputs or ``None``, and ``audio`` is copied from the source
        sample when present.
    """
    from megatron.bridge.data.energon.task_encoder_utils import (
        _images_to_pil,
        _videos_to_pil,
        cook_chatml_sample,
    )

    imgs = getattr(sample, "imgs", None)
    videos = getattr(sample, "videos", None)
    return NormalizedVLMSample(
        conversation=cook_chatml_sample(sample.conversation),
        images=_images_to_pil(imgs) if imgs is not None and len(imgs) > 0 else None,
        videos=_videos_to_pil(videos) if videos is not None and len(videos) > 0 else None,
        audio=getattr(sample, "audio", None),
    )


def normalize_hf_vlm_example(example: Mapping[str, Any]) -> NormalizedVLMSample:
    """Normalize a HF-style VLM dataset example into the shared sample contract.

    Expected input format:
        ``example`` must contain ``"conversation"`` as a structured list of chat
        turns already produced by an HF dataset maker, for example::

            {
                "conversation": [
                    {"role": "user", "content": [{"type": "image", "image": img}, {"type": "text", "text": "Q"}]},
                    {"role": "assistant", "content": [{"type": "text", "text": "A"}]},
                ],
                "audio": optional_audio,
            }

        Optional top-level ``images``/``image`` and ``videos``/``video`` fields
        are accepted for maker variants that do not embed media inline in the
        conversation.

    Output format:
        Returns ``NormalizedVLMSample`` with a deep-copied structured
        ``conversation`` list, optional list-valued ``images`` and ``videos``
        payloads, and optional ``audio``.  The adapter does not call
        ``cook_chatml_sample`` because HF makers have already normalized the chat
        schema.

    Raises:
        ValueError: If ``example["conversation"]`` is missing or is not a list.
    """
    conversation = example.get("conversation")
    if not isinstance(conversation, list):
        raise ValueError("HF VLM examples must contain a list-valued 'conversation' field.")

    images = example.get("images")
    if images is None and "image" in example:
        images = [example["image"]]
    videos = example.get("videos")
    if videos is None and "video" in example:
        videos = [example["video"]]

    return NormalizedVLMSample(
        conversation=copy.deepcopy(conversation),
        images=images,
        videos=videos,
        audio=example.get("audio"),
    )


def normalized_vlm_sample_to_hf_example(
    sample: NormalizedVLMSample,
    *,
    media_first: bool = False,
) -> dict[str, Any]:
    """Convert a normalized VLM sample into the HF-style collate example schema.

    Expected input format:
        ``sample`` follows ``NormalizedVLMSample``: ``conversation`` is a list of
        chat turns, and optional ``images``/``videos`` contain processor-ready
        media payloads such as PIL images or decoded video frame lists.  Text
        turns may contain literal ``<image>`` / ``<video>`` placeholders.

    Output format:
        Returns a dictionary suitable for VLM HF collate functions::

            {
                "conversation": [
                    {
                        "role": "user",
                        "content": [
                            {"type": "image", "image": image_obj},
                            {"type": "text", "text": "describe"},
                        ],
                    },
                    {"role": "assistant", "content": [{"type": "text", "text": "answer"}]},
                ],
                "images": [image_obj],   # present when sample.images is not None
                "videos": [video_obj],   # present when sample.videos is not None
                "audio": audio_obj,      # present when sample.audio is not None
            }

        Inline media parts are populated from ``sample.images`` and
        ``sample.videos`` in placeholder order.  When ``media_first=True``,
        media parts are moved before text parts within each turn to preserve
        Qwen Energon's legacy media-before-text ordering while still using the
        shared HF collate function.
    """
    images = list(sample.images) if sample.images is not None else []
    videos = list(sample.videos) if sample.videos is not None else []
    image_idx = 0
    video_idx = 0

    def _media_part(media_type: str) -> dict[str, Any]:
        nonlocal image_idx, video_idx
        part: dict[str, Any] = {"type": media_type}
        if media_type == "image":
            if image_idx < len(images):
                part["image"] = images[image_idx]
                image_idx += 1
        elif media_type == "video" and video_idx < len(videos):
            part["video"] = videos[video_idx]
            video_idx += 1
        return part

    def _normalize_content(content: Any) -> Any:
        nonlocal image_idx, video_idx
        if isinstance(content, list):
            parts: list[dict[str, Any] | str] = []
            for item in content:
                if not isinstance(item, Mapping):
                    parts.append(item)
                    continue
                item_copy = dict(item)
                item_type = item_copy.get("type")
                if item_type == "image" and "image" not in item_copy and image_idx < len(images):
                    item_copy["image"] = images[image_idx]
                    image_idx += 1
                elif item_type == "video" and "video" not in item_copy and video_idx < len(videos):
                    item_copy["video"] = videos[video_idx]
                    video_idx += 1
                parts.append(item_copy)
            if media_first:
                media_parts = [
                    part for part in parts if isinstance(part, Mapping) and part.get("type") in ("image", "video")
                ]
                other_parts = [part for part in parts if part not in media_parts]
                return media_parts + other_parts
            return parts

        if not isinstance(content, str) or ("<image>" not in content and "<video>" not in content):
            return copy.deepcopy(content)

        pieces = re.split(r"(<image>|<video>)", content)
        parts = []
        for piece in pieces:
            if piece == "<image>":
                parts.append(_media_part("image"))
            elif piece == "<video>":
                parts.append(_media_part("video"))
            elif piece:
                parts.append({"type": "text", "text": piece.strip(" ")})
        if media_first:
            media_parts = [part for part in parts if part.get("type") in ("image", "video")]
            text_parts = [part for part in parts if part.get("type") not in ("image", "video")]
            return media_parts + text_parts
        return parts

    conversation = []
    for turn in sample.conversation:
        turn_copy = dict(turn)
        turn_copy["content"] = _normalize_content(turn_copy.get("content", ""))
        conversation.append(turn_copy)

    example: dict[str, Any] = {"conversation": conversation}
    if sample.images is not None:
        example["images"] = images
    if sample.videos is not None:
        example["videos"] = videos
    if sample.audio is not None:
        example["audio"] = sample.audio
    return example


def get_processor_tokenizer(processor: Any) -> Any:
    """Return the tokenizer attached to a processor, or the object itself."""
    return getattr(processor, "tokenizer", processor)


def _as_token_id_list(token_ids: Any) -> list[int]:
    if token_ids is None:
        return []
    if isinstance(token_ids, torch.Tensor):
        token_ids = token_ids.detach().cpu().tolist()
    if isinstance(token_ids, (list, tuple)) and token_ids and isinstance(token_ids[0], torch.Tensor):
        token_ids = [item.detach().cpu().tolist() for item in token_ids]
    if isinstance(token_ids, (list, tuple)) and token_ids and isinstance(token_ids[0], (list, tuple)):
        if len(token_ids) != 1:
            return []
        token_ids = token_ids[0]
    return [int(token_id) for token_id in token_ids]


def _conversation_from_example(
    example_or_conversation: Mapping[str, Any] | Sequence[Mapping[str, Any]],
) -> Sequence[Mapping[str, Any]]:
    if isinstance(example_or_conversation, Mapping):
        conversation = example_or_conversation.get("conversation", [])
        return conversation if isinstance(conversation, Sequence) and not isinstance(conversation, str) else []
    return example_or_conversation


def chat_template_kwargs_from_example(
    example_or_conversation: Mapping[str, Any] | Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    """Return optional HF chat-template kwargs stored alongside a conversation."""
    if not isinstance(example_or_conversation, Mapping):
        return {}

    kwargs: dict[str, Any] = {}
    tools = example_or_conversation.get("tools")
    if tools is not None:
        kwargs["tools"] = tools
    return kwargs


def find_token_span(sequence: Sequence[int] | torch.Tensor, pattern: Sequence[int], start: int = 0) -> tuple[int, int]:
    """Find the first ``[start, end)`` token span matching ``pattern``.

    Args:
        sequence: Token id sequence to search.
        pattern: Token id pattern to locate.
        start: Index to begin searching from.

    Returns:
        ``(start, end)`` for the first match, or ``(-1, -1)`` when no match exists.
    """
    ids = _as_token_id_list(sequence)
    pat = list(pattern)
    if not pat or start >= len(ids):
        return -1, -1

    end_limit = len(ids) - len(pat) + 1
    for idx in range(start, max(end_limit, start)):
        if ids[idx : idx + len(pat)] == pat:
            return idx, idx + len(pat)
    return -1, -1


def gather_assistant_text_segments(
    example_or_conversation: Mapping[str, Any] | Sequence[Mapping[str, Any]],
) -> list[str]:
    """Extract assistant text segments from a structured VLM conversation."""
    conversation = _conversation_from_example(example_or_conversation)
    texts: list[str] = []
    for turn in conversation:
        if turn.get("role") != "assistant":
            continue
        content = turn.get("content", "")
        text_parts: list[str] = []
        if isinstance(content, list):
            for part in content:
                if isinstance(part, Mapping) and part.get("type") == "text" and isinstance(part.get("text"), str):
                    text_parts.append(part["text"])
                elif isinstance(part, str):
                    text_parts.append(part)
        elif isinstance(content, str):
            text_parts.append(content)
        if text_parts:
            texts.append("".join(text_parts))
    return texts


def tokenize_text_without_special_tokens(tokenizer: Any, text: str) -> list[int]:
    """Tokenize text using a HF-like tokenizer without adding special tokens."""
    try:
        if hasattr(tokenizer, "encode"):
            tokens = tokenizer.encode(text, add_special_tokens=False)
        elif callable(tokenizer):
            tokens = tokenizer(text, add_special_tokens=False)["input_ids"]
        else:
            return []
    except (KeyError, TypeError, ValueError):
        return []
    return _as_token_id_list(tokens)


def assistant_mask_boundary_config_from_markers(
    processor: Any,
    *,
    assistant_start: str,
    assistant_end: str,
    loss_roles: Sequence[str] = (CHATML_ASSISTANT_ROLE,),
    include_start_tokens_for_roles: Sequence[str] = (),
    include_end_tokens_for_roles: Sequence[str] = (CHATML_ASSISTANT_ROLE,),
    trim_leading_token_ids: Sequence[int] = (),
) -> AssistantMaskBoundaryConfig:
    """Build explicit assistant boundary config from model-declared marker strings."""
    tokenizer = get_processor_tokenizer(processor)
    start_tokens = tokenize_text_without_special_tokens(tokenizer, assistant_start)
    end_tokens = tokenize_text_without_special_tokens(tokenizer, assistant_end)
    if not start_tokens or not end_tokens:
        raise ValueError(
            "Unable to tokenize assistant loss-mask boundary markers. "
            "Check the model collator's assistant_start and assistant_end markers."
        )
    return AssistantMaskBoundaryConfig(
        role_start_tokens={CHATML_ASSISTANT_ROLE: start_tokens},
        role_end_tokens={CHATML_ASSISTANT_ROLE: end_tokens},
        loss_roles=loss_roles,
        include_start_tokens_for_roles=include_start_tokens_for_roles,
        include_end_tokens_for_roles=include_end_tokens_for_roles,
        trim_leading_token_ids=trim_leading_token_ids,
    )


def _apply_skipped_tokens(mask: torch.Tensor, ids: Sequence[int], skipped_tokens: torch.Tensor | None) -> None:
    if skipped_tokens is None or skipped_tokens.numel() == 0:
        return
    skipped = set(skipped_tokens.detach().cpu().tolist())
    for idx, token_id in enumerate(ids):
        if token_id in skipped:
            mask[idx] = 0.0


def _warn_if_all_masked(
    mask: torch.Tensor,
    example_or_conversation: Mapping[str, Any] | Sequence[Mapping[str, Any]],
    *,
    warn_on_all_masked: bool,
) -> None:
    if warn_on_all_masked and len(mask) > 0 and float(mask.sum().item()) == 0.0:
        warnings.warn("*" * 100, stacklevel=3)
        warnings.warn(f"All tokens are masked for example:\n{example_or_conversation}.", stacklevel=3)
        warnings.warn("*" * 100, stacklevel=3)


def _get_chat_template(*objects: Any) -> str | None:
    for obj in objects:
        template = getattr(obj, "chat_template", None)
        if isinstance(template, str):
            return template
    return None


def _assistant_mask_from_hf_chat_template(
    example_or_conversation: Mapping[str, Any] | Sequence[Mapping[str, Any]],
    ids: Sequence[int],
    processor: Any,
    tokenizer: Any,
) -> torch.Tensor | None:
    """Return HF generation-block assistant mask when it aligns to ``ids``."""
    conversation = _conversation_from_example(example_or_conversation)
    chat_template_kwargs = chat_template_kwargs_from_example(example_or_conversation)
    seen: set[int] = set()
    for template_owner in (tokenizer, processor):
        if id(template_owner) in seen:
            continue
        seen.add(id(template_owner))
        apply_chat_template = getattr(template_owner, "apply_chat_template", None)
        template = _get_chat_template(template_owner)
        if apply_chat_template is None or template is None or GENERATION_REGEX.search(template) is None:
            continue

        try:
            tokenized_chat = apply_chat_template(
                conversation,
                tokenize=True,
                add_generation_prompt=False,
                return_dict=True,
                return_assistant_tokens_mask=True,
                **chat_template_kwargs,
            )
        except (AttributeError, KeyError, TypeError, ValueError):
            continue

        if not isinstance(tokenized_chat, Mapping):
            continue
        if "assistant_masks" not in tokenized_chat:
            continue
        candidate_ids = _as_token_id_list(tokenized_chat.get("input_ids"))
        assistant_mask = _as_token_id_list(tokenized_chat["assistant_masks"])
        aligned_mask = _align_assistant_mask_to_padded_ids(candidate_ids, assistant_mask, ids, tokenizer)
        if aligned_mask is None:
            continue
        return torch.tensor(aligned_mask, dtype=torch.float32)
    return None


def _align_assistant_mask_to_padded_ids(
    candidate_ids: Sequence[int],
    assistant_mask: Sequence[int],
    ids: Sequence[int],
    tokenizer: Any,
) -> list[int] | None:
    """Align an HF assistant mask to possibly padded processor batch ids."""
    target_ids = list(ids)
    source_ids = list(candidate_ids)
    source_mask = [int(mask_value) for mask_value in assistant_mask]
    if len(source_ids) != len(source_mask):
        return None
    if source_ids == target_ids:
        return source_mask

    pad_token_id = getattr(tokenizer, "pad_token_id", None)
    if pad_token_id is None or len(source_ids) > len(target_ids):
        return None

    pad_len = len(target_ids) - len(source_ids)
    if target_ids[: len(source_ids)] == source_ids and all(
        token_id == pad_token_id for token_id in target_ids[-pad_len:]
    ):
        return source_mask + [0] * pad_len
    if target_ids[pad_len:] == source_ids and all(token_id == pad_token_id for token_id in target_ids[:pad_len]):
        return [0] * pad_len + source_mask
    return None


def _token_map_from_boundary_config(token_map: Mapping[str, Sequence[int]] | None) -> dict[str, list[int]]:
    if token_map is None:
        return {}
    return {
        role: token_ids for role, raw_token_ids in token_map.items() if (token_ids := _as_token_id_list(raw_token_ids))
    }


def _trim_leading_token_ids(
    ids: Sequence[int],
    start: int,
    end: int,
    trim_token_ids: Sequence[int],
) -> int:
    trim_tokens = set(trim_token_ids)
    idx = start
    while idx < end and ids[idx] in trim_tokens:
        idx += 1
    return idx


def _assistant_mask_from_boundary_config(
    ids: Sequence[int],
    boundary_config: AssistantMaskBoundaryConfig,
) -> torch.Tensor | None:
    role_start_tokens = _token_map_from_boundary_config(boundary_config.role_start_tokens)
    role_end_tokens = _token_map_from_boundary_config(boundary_config.role_end_tokens)
    loss_roles = set(boundary_config.loss_roles)
    if not role_start_tokens or not role_end_tokens or not loss_roles:
        raise ValueError(
            "AssistantMaskBoundaryConfig must provide non-empty role_start_tokens, role_end_tokens, and loss_roles."
        )
    missing_role_end_tokens = set(role_start_tokens) - set(role_end_tokens)
    if missing_role_end_tokens:
        raise ValueError(
            "AssistantMaskBoundaryConfig role_end_tokens is missing entries for roles: "
            f"{sorted(missing_role_end_tokens)}."
        )

    markers: list[tuple[int, str, int]] = []
    for role, start_tokens in role_start_tokens.items():
        search_start = 0
        while search_start < len(ids):
            start_pos, after_start = find_token_span(ids, start_tokens, search_start)
            if start_pos < 0:
                break
            markers.append((start_pos, role, len(start_tokens)))
            search_start = after_start
    if not markers:
        return None

    markers.sort(key=lambda marker: (marker[0], -marker[2]))
    deduped_markers: list[tuple[int, str, int]] = []
    for marker in markers:
        if deduped_markers and marker[0] == deduped_markers[-1][0]:
            continue
        deduped_markers.append(marker)

    include_start_tokens_for_roles = set(boundary_config.include_start_tokens_for_roles)
    include_end_tokens_for_roles = set(boundary_config.include_end_tokens_for_roles)
    trim_token_ids = _as_token_id_list(boundary_config.trim_leading_token_ids)

    mask = torch.zeros(len(ids), dtype=torch.float32)
    found_loss_segment = False
    for marker_idx, (start_pos, role, marker_len) in enumerate(deduped_markers):
        content_start = start_pos + marker_len
        next_marker_start = deduped_markers[marker_idx + 1][0] if marker_idx + 1 < len(deduped_markers) else len(ids)
        role_end_pattern = role_end_tokens.get(role, [])
        role_end_span = None
        content_end = next_marker_start
        if role_end_pattern:
            end_start, after_end = find_token_span(ids, role_end_pattern, content_start)
            if end_start >= 0 and end_start < next_marker_start:
                content_end = end_start
                role_end_span = (end_start, after_end)

        if role not in loss_roles:
            continue

        found_loss_segment = True
        segment_start = _trim_leading_token_ids(ids, content_start, content_end, trim_token_ids)
        if segment_start < content_end:
            mask[segment_start:content_end] = 1.0

        if role in include_start_tokens_for_roles:
            mask[start_pos:content_start] = 1.0
        if role in include_end_tokens_for_roles and role_end_span is not None:
            mask[role_end_span[0] : role_end_span[1]] = 1.0

    return mask if found_loss_segment else None


def build_assistant_loss_mask(
    example_or_conversation: Mapping[str, Any] | Sequence[Mapping[str, Any]],
    input_ids: Sequence[int] | torch.Tensor,
    processor: Any,
    skipped_tokens: torch.Tensor | None = None,
    *,
    boundary_config: AssistantMaskBoundaryConfig | None = None,
    warn_on_all_masked: bool = True,
) -> torch.Tensor:
    """Build an unshifted assistant-only loss mask.

    The preferred path uses HF chat templates with ``{% generation %}`` blocks.
    When those are unavailable, callers may provide ``boundary_config`` to scan
    explicit role token boundaries from rendered ``input_ids``.

    Raises:
        ValueError: If neither a HF generation mask nor a valid explicit
            boundary mask can be built.
    """
    tokenizer = get_processor_tokenizer(processor)
    ids = _as_token_id_list(input_ids)

    mask = _assistant_mask_from_hf_chat_template(example_or_conversation, ids, processor, tokenizer)
    if mask is None and boundary_config is not None:
        mask = _assistant_mask_from_boundary_config(ids, boundary_config)
    if mask is None:
        if boundary_config is None:
            raise ValueError(
                "Unable to build assistant loss mask. Provide a processor/tokenizer chat_template with "
                "{% generation %} blocks that returns assistant_masks, or pass AssistantMaskBoundaryConfig "
                "with explicit role token boundaries."
            )
        raise ValueError("AssistantMaskBoundaryConfig did not match any loss-contributing spans in input_ids.")

    _apply_skipped_tokens(mask, ids, skipped_tokens)
    _warn_if_all_masked(mask, example_or_conversation, warn_on_all_masked=warn_on_all_masked)
    return mask


def build_shifted_labels_and_loss_mask(
    input_ids: torch.Tensor,
    assistant_loss_mask: torch.Tensor,
    skipped_tokens: torch.Tensor | None = None,
    *,
    ignore_index: int = IGNORE_INDEX,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Build next-token labels and shifted loss mask for Megatron training."""
    squeeze = input_ids.dim() == 1
    ids = input_ids.unsqueeze(0) if squeeze else input_ids
    mask = assistant_loss_mask.unsqueeze(0) if assistant_loss_mask.dim() == 1 else assistant_loss_mask
    mask = mask.to(device=ids.device, dtype=torch.float32)

    labels = ids.clone()[:, 1:].contiguous()
    labels = torch.cat([labels, ignore_index * torch.ones_like(labels[:, :1])], dim=1)

    if skipped_tokens is not None and skipped_tokens.numel() > 0:
        labels = labels.masked_fill(torch.isin(labels, skipped_tokens.to(device=labels.device)), ignore_index)

    shifted_loss_mask = torch.cat([mask[:, 1:], torch.zeros_like(mask[:, :1])], dim=1)
    labels = labels.masked_fill(shifted_loss_mask == 0, ignore_index)

    if squeeze:
        return labels[0].contiguous(), shifted_loss_mask[0].contiguous()
    return labels.contiguous(), shifted_loss_mask.contiguous()


def apply_assistant_labels_to_batch(
    batch: MutableMapping[str, Any],
    examples: Sequence[Mapping[str, Any]],
    processor: Any,
    skipped_tokens: torch.Tensor,
    *,
    boundary_config: AssistantMaskBoundaryConfig | None = None,
    unmask_last_token: bool = False,
) -> None:
    """Attach ``labels`` and ``loss_mask`` to a collated HF VLM batch."""
    loss_masks = [
        build_assistant_loss_mask(
            example,
            input_ids,
            processor,
            skipped_tokens,
            boundary_config=boundary_config,
        )
        for example, input_ids in zip(examples, batch["input_ids"])
    ]
    loss_mask_t = torch.stack(loss_masks).to(device=batch["input_ids"].device, dtype=torch.float32)
    if unmask_last_token and loss_mask_t.numel() > 0:
        loss_mask_t[:, -1] = 1.0
    labels, shifted_loss_mask = build_shifted_labels_and_loss_mask(batch["input_ids"], loss_mask_t, skipped_tokens)
    batch["labels"] = labels
    batch["loss_mask"] = shifted_loss_mask


def ensure_position_ids(batch: MutableMapping[str, Any]) -> None:
    """Ensure a collated batch has 2D position IDs."""
    if "position_ids" in batch or "input_ids" not in batch:
        return
    batch_size, seq_len = batch["input_ids"].shape
    batch["position_ids"] = (
        torch.arange(seq_len, device=batch["input_ids"].device)
        .unsqueeze(0)
        .expand(batch_size, -1)
        .clone()
        .contiguous()
    )


def pop_generic_visual_inputs(
    batch: MutableMapping[str, Any],
    visual_keys: Sequence[str],
) -> GenericVisualInputs | None:
    """Move processor visual tensor keys into ``GenericVisualInputs``."""
    visual_kwargs = {}
    for key in visual_keys:
        if key in batch:
            visual_kwargs[key] = batch.pop(key)
    return GenericVisualInputs(**visual_kwargs) if visual_kwargs else None
